apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uber-like-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-http2: "true"  # Optional: Enable HTTP/2 support
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"  # Specify protocol if necessary
spec:
  rules:
  - host: your-app-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uber-like-app-frontend  # Match the Rollout service name
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: uber-like-app-backend  # Match the Rollout service name
            port:
              number: 8080
