apiVersion: v1
kind: Service
metadata:
  name: uber-like-app-frontend  # Updated to match Ingress
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: uber-like-app-backend  # Updated to match Ingress
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
